import type { Metadata } from "next";
import { Bricolage_Grotesque} from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const bricolage_grotesque = Bricolage_Grotesque({ subsets: ["latin"],  variable: "--font-Bricolage_Grotesque" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
          "min-h-screen bg-background font-Bricolage_Grotesque antialiased",
          bricolage_grotesque.variable
        )}>{children}</body>
    </html>
  );
}
